/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.pmix.ui;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int even_stripe=0x7f020002;
        public static final int gmpcnocover=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int odd_stripe=0x7f020003;
        public static final int solid_blue=0x7f020005;
        public static final int solid_green=0x7f020006;
        public static final int solid_red=0x7f020004;
    }
    public static final class id {
        public static final int albumCover=0x7f050004;
        public static final int albumName=0x7f050002;
        public static final int artistName=0x7f050001;
        public static final int back=0x7f050006;
        public static final int forward=0x7f050008;
        public static final int label1=0x7f05000e;
        public static final int mainInfo=0x7f05000d;
        public static final int next=0x7f050009;
        public static final int ok=0x7f050010;
        public static final int playpause=0x7f050007;
        public static final int prev=0x7f050005;
        public static final int serverAddress=0x7f05000f;
        public static final int songName=0x7f050003;
        public static final int text1=0x7f050000;
        public static final int track=0x7f05000b;
        public static final int trackTime=0x7f05000a;
        public static final int volume=0x7f05000c;
    }
    public static final class layout {
        public static final int albums=0x7f030000;
        public static final int artist_row=0x7f030001;
        public static final int artists=0x7f030002;
        public static final int files=0x7f030003;
        public static final int main=0x7f030004;
        public static final int settings=0x7f030005;
    }
    public static final class string {
        public static final int albums=0x7f040004;
        public static final int app_name=0x7f040000;
        public static final int artists=0x7f040001;
        public static final int back=0x7f04000d;
        public static final int files=0x7f040003;
        public static final int forward=0x7f04000e;
        public static final int next=0x7f04000c;
        public static final int ok=0x7f040008;
        public static final int playlists=0x7f040002;
        public static final int playpause=0x7f04000b;
        public static final int prev=0x7f04000a;
        public static final int progressbar_1_minus=0x7f040010;
        public static final int progressbar_1_plus=0x7f04000f;
        public static final int serverAddress=0x7f040009;
        public static final int settings=0x7f040005;
        public static final int track=0x7f040007;
        public static final int volume=0x7f040006;
    }
}
